targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      graphql_codegen:
        options:
          clients:
            - graphql
            - graphql_flutter
          scalars:
            ISODateTime:
              type: DateTime
            JSON:
              type: Map<String, dynamic>
