targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      graphql_codegen:
        options:
          addTypenameExcludedPaths:
            - subscription
          outputDirectory: __generated__
          clients:
            - graphql
            - graphql_flutter
          scalars:
            ISODateTime:
              type: DateTime
            JSON:
              type: Map<String, dynamic>
            Upload:
              type: MultipartFile
              fromJsonFunctionName: fileFromJson
              toJsonFunctionName: fileToJson
              import: package:tachidesk_sorayomi/src/utils/misc/scalars.dart
            LongString:
              type: String
              fromJsonFunctionName: longStringFromJson
              toJsonFunctionName: longStringToJson
              import: package:tachidesk_sorayomi/src/utils/misc/scalars.dart
            Cursor:
              type: int
              fromJsonFunctionName: cursorFromJson
              toJsonFunctionName: cursorToJson
              import: package:tachidesk_sorayomi/src/utils/misc/scalars.dart
